# Dockerfile for Mo Cam container. 
# 
# Author: collantes.xavier@gmail.com 


# Use image that is amd64 compatible. 
FROM python:bullseye

WORKDIR /mocam

# Rclone config generated by `rclone config`.
ENV RCLONE_CONFIG="./rclone.conf" 

# By default, Motion will store video and images.   
ENV SAVE_SOURCE="/motion/"

RUN apt-get update -y; apt-get upgrade -y; \
    apt-get install unzip -y; \
    apt-get install motion -y

#ADD https://www.python.org/ftp/python/3.10.7/Python-3.10.7.tgz Python-3.10.7.tgz 

#RUN unzip Python-3.10.7.tgz 

# Get rclone for file push to cloud. 
# https://rclone.org/downloads 
RUN curl https://rclone.org/install.sh | bash 

# Configure settings before generating image for Mo Cam. 
COPY motion.conf /etc/motion/motion.conf

# Config for rclone to transfer file to Mega. 
COPY ${RCLONE_CONFIG} /mocam/rclone.conf

# Script to start motion. 
COPY start_motion.sh /mocam/.
  
# Script runs the required background processes. 
COPY start_mocam.sh /mocam/.

# Script to run after each event. 
COPY event_end_script.sh /mocam/. 

# For debugging. 
COPY test_script.sh /mocam/.

RUN chmod +x /mocam/*.sh

# By default not exposing streams for enhanced security. 
# EXPOSE 6001 
# EXPOSE 6002

ENTRYPOINT ["/mocam/start_mocam.sh"]
