# Dockerfile for Mo Cam container. 
# 
# Author: collantes.xavier@gmail.com 


# Using RPI4 image to closely resemble host OS.  
FROM balenalib/raspberrypi4-64

# Rclone config generated by `rclone config`.
ARG rclone_config="./rclone.conf" 

WORKDIR /mocam

RUN apt-get update -y; apt-get upgrade -y; \
    apt-get install unzip -y; \
    apt-get install motion -y

# Get rclone for file push to cloud. 
# https://rclone.org/downloads 
RUN curl https://rclone.org/install.sh | bash 

# Configure settings before generating image for Mo Cam. 
COPY motion.conf /etc/motion/motion.conf

# Config for rclone to transfer file to Mega. 
COPY ${rclone_config} /mocam/rclone.conf

# Script to start process to copy files to destination. 
COPY start_sync.sh /mocam/. 

# Script to start motion. 
COPY start_motion.sh /mocam/.
  
# Script runs the required background processes. 
COPY run.sh /mocam/.

RUN chmod +x /mocam/*.sh

# By default not exposing streams for enhanced security. 
# EXPOSE 6001 
# EXPOSE 6002

ENTRYPOINT ["/mocam/run.sh"]
